### ISSUE TITLE
[Upload service] Mass upload with uppy does not work anymore

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#115]
The following error occurs when using the mass upload with uppy:
An error has occurred. 
`array_key_exists(): Argument #2 ($array) must be of type array, null given in administrator\components\com_joomgallery\src\Service\Uploader\SingleUploader.php:241`
The problem has probably occurred since the merging of this PR: https://github.com/JoomGalleryfriends/JG4-dev/pull/110

**Comment by reni68** [comment]
I'm afraid I have to confirm that.
After my longer break here as a tester, I wanted to see what the status was and installed the main.zip => this error.

**Comment by AlexanderSupp** [comment]
Me too. PHP 8.0.
BTW:
I set up my Joomla on my Synology with PHP 7.4.3 new.
I got several errors, such as
- in categories the password will already automatically set
- Creation date of image not set, but defined 
- Overwrite image title in NEW image will ignore.
These things work fine with PHP 8.0 on WampServer.
So I assume the reason is PHP 7.4.3 or my ugly Synology.

**Comment by AlexanderSupp** [comment]
Mystery. On my other Synology with PHP 8.0 point 1 above work correct, point 2 also an error and point 3 work correct.

**Comment by AlexanderSupp** [comment]
For further tests, it is important that this function will work.

**Comment by MrMusic** [comment]
Closed as completed
