### ISSUE TITLE
Determining the correct rating of an image

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#144]
Currently, the correct rating (average) of an image is not displayed in the frontend and backend.
The number of ratings and the sum of the ratings are stored in the database.
Example: The following ratings are given for a image
6 x 5 stars = total 30
2 x 4 stars = total 8
3 x 3 stars = total 9
The number of ratings in the database is '11'. The votesum is '47'. The arithmetic mean would be '4.27'.

In JoomGallery 3.6 there was the function `JoomHelper::getRating(imageid)` which calculated the average rating of a image.
In the configuration you could set whether the arithmetic mean or weighted according to Bayes should be calculated for the rating. Personally, the arithmetic mean would be sufficient for me.
Should this function also exist in JG4 or should the calculation first take place in the view or template file (redundant)?
I think it would be helpful if the average rating were available globally for the images in frontend and backend.

**Comment by reilldesign** [comment]
This works fine even when the menu alias is called. As long as there is no other recommendation i use this way.

**Comment by AlexanderSupp** [comment]
People strive for recognition, assessment and further development. On the other hand, he would like to judge and express his opinion. And that's why there is this wonderful opportunity for communication, especially on the Internet. You can like, dislike, rate and comment.
Especially with photo galleries, such a possibility is an essential part of such a system.

Without a sophisticated rating system, a photo gallery is meaningless for a community.
And that's why I can't migrate to the new JoomGallery without a rating system.

JoomGallery 3.6. impresses with one of the best rating systems.
The rating scale can be offered on 1 to 10 points. In addition to the pure average rating, an evaluation taking into account the number of votes can also be offered (Bayes). If, for example, if a photo is rated 10 by one reviewer and another photo is rated 9 by 10 reviewers, the photo with only one review wins. In many cases, the photo with one rating is not worth paying attention to at all for most reviewers. Here the result is distorted.
Another advantage of JoomGallery 3.6. is, that according to the settings only logged-in users can rate.

The photo friends Much use the Bayes rating function with a scale of 1 to 10, only for registered users.

An assessment also includes the possibility of justifying the assessment or even simply stating the potential for improvement without an assessment. This is done through a comment. Both options are in JoomGallery 3.6. solved excellently.

Details here: http://joomgallery4.fotofreunde-much.de/en/requirements/the-photo-club

**Comment by MrMusic** [comment]
@AlexanderSupp  Thank you for your detailed comment.
I would not have guessed that someone would use the 'Bayes' rating and also move the rating scale to 10.
