### ISSUE TITLE
ausgeblendete Kategorien

### ISSUE THREAD

**Issue by JochenEb** [JoomGalleryfriends/JG4-dev#170]
Wenn eine Kategorie ausgeblendet wird, bleibt diese in "List of Categorie" weiterhin sichtbar, wird aber bei "Veröffentlicht" mit einem "X" gekennzeichnet. In "Categorie View" wird diese nicht angezeigt.
Ist das so gewollt?

![bild1](https://github.com/JoomGalleryfriends/JG4-dev/assets/75810945/261f5b48-af6b-41f4-878d-50cc1fdba37b)
![bild2](https://github.com/JoomGalleryfriends/JG4-dev/assets/75810945/f2a1c7c0-3ca7-4fb2-9e7e-ceca4d98facc)
![bild3](https://github.com/JoomGalleryfriends/JG4-dev/assets/75810945/2262d403-eb00-4a1a-9412-a5949b7c76e5)

Wenn die Kategorie nur für "registered" zugänglich sein soll, wird diese bei "Categorie View" nicht angezeigt, bei "List of Categorie" aber als veröffentlicht markiert.

**Comment by MrMusic** [comment]
I think 'List of categories' is a default view that was created automatically and it is not sure if this view will stay like this. 
There, for example, the access level is not taken into account, but it is in the 'category view'.

@Elfangor93 Should 'List of categories' also exist in the future for guests? Because then some changes would have to be made to it, especially because of the access rights.

>If the category should only be accessible for "registered", it is not displayed in "Category View", but is marked as published in "List of Categorie".

You must differentiate between Status published/unpublished and the access level, e.g. 'Registered'. These are two different things.

**Comment by Elfangor93** [comment]
Access rights in the frontend have to be reworked anyway. Under the hood, the frontend is still very rudimentary...

**Comment by Elfangor93** [comment]
Close this since it is not really an issue.
