### ISSUE TITLE
PHP warning from the JoomGallery System Plugin on Joomla 5

### ISSUE THREAD

**Issue by jobrusche** [JoomGalleryfriends/JG4-dev#272]
Joomla 5.2.0 on Wampserver PHP 8.2.19
Joomgallery JG4-dev-4.0.0-alpha3  : fresh install

Click on "Start" in installation completed screen
Same display with debug on or off

Screeenshots
![Schermafbeelding 2024-10-20 142321](https://github.com/user-attachments/assets/789608e3-8af8-4178-a40d-3ac3995dd6b9)
![Schermafbeelding 2024-10-20 142833](https://github.com/user-attachments/assets/4fe40eab-6fbb-4f56-84df-0575284e3408)
![Schermafbeelding 2024-10-20 143130](https://github.com/user-attachments/assets/7e367f7e-5d7f-491c-94bd-3d5454eefb56)

**Comment by Elfangor93** [comment]
This php warning comes from the way I realized the plugin to be compatible to both Joomla v4.x and Joomla v5.x. It first tries to do it the Joomla 4 way and if it does not work it does it the Joomla 5 way.

While trying it the Joomla 4 way it will produce a php warning when running on Joomla 5. But this is not a porblem in my point of view as php warnings should be disabled in producitive systems anyway.
So this issue is feature not bug ;-)

**Comment by eumel1602** [comment]
nur als anmerkung. 
Online / php 8.2.x alpha 3 auf eine geupdate Joomla 5.2. installiert -> Fehler/Feature/bug erscheint nicht...

**Comment by MrMusic** [comment]
>Fehler erscheint nur, wenn Fehler berichten auf maximum steht in der Joomla global config.

oder auf 'simple'.

**Comment by jobrusche** [comment]
Server 'Error reporting' set to 'none' in **global configuration** solved this
