### ISSUE TITLE
[IMGtools service]: Wrong error message Unsupported image filetype

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#62]
Issue detected by @szepty-ziemi
-----

1. Selected IM and it seems that JG is detecting it correctly, even if I don't specify the path:
![grafik](https://user-images.githubusercontent.com/39154009/210221889-7c27e940-9b07-4d36-8d19-65f522d1aad9.png)
2. Then I'm trying to upload image and it fails:

Save failed with the following error:
Unsupported image filetype.

![grafik](https://user-images.githubusercontent.com/39154009/210221925-030183cf-3c53-4ba4-8bca-1c22f068aef7.png)
Previously I didn't have to specify the path (previous test versions) and IM worked fine.
https://prnt.sc/gjbixfIRq-Cn

**Comment by AlexanderSupp** [comment]
Take a look at issue #36 and my comment from Sep 08 and Nov 11. It's from my point of view, the same problem.

**Comment by MrMusic** [comment]
The cause is probably in the function getTypes() in IMtools.php. This function does not return any values with imagemagick v6.x.

Line934:
`@\exec(\trim($this->impath).'convert -version', $output);`

A debug of $output returns the following array:
```
Array
(
    [0] => Version: ImageMagick 6.9.10-68 Q16 x86_64 2021-10-14 https://imagemagick.org
    [1] => Copyright: © 1999-2019 ImageMagick Studio LLC
    [2] => License: https://imagemagick.org/script/license.php
    [3] => Features: Cipher DPC Modules OpenMP(3.1)
    [4] => Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff wmf x xml zlib
)
```
I guess you need different functions for ImageMagick v6.x and v7.x ?

**Comment by AlexanderSupp** [comment]
I checked once more the situation in my environments.
=== Provider DomainFactory ===
Joomla 3.10.x with JG 3.6 for Fotofreunde-Much.de
PHP-Version 8.1.14
Imagick compiled with ImageMagick version ImageMagick 6.9.12-34 Q16 x86_64 2021-12-22
Imagick using ImageMagick library version ImageMagick 6.9.12-72 Q16 x86_64 17615
ImageMagick works correct.

Joomla 4.2.6 with JG 4.0 for Test.Wanderboys.de
PHP and ImageMagick same as above
ImageMagick failed
Save failed with the following error: Unsupported image filetype.

JG4 must provide different versions, so that I am able to upgrade from the old to the new system.
Currently, only version ImageMagick-7.1.0-Q16-HDRI works.
Tested with WampServer and my Synology DS214Play.
